import * as D from './declaration.js';

export function simulateCombat(playerState,wave,cp,boss=null,mode=D.RANGED_MODE.A,opts={}){
  if(mode===D.RANGED_MODE.B&&!opts.modeBConfig)throw new Error('DECLARATION MISSING: Mode B ranged enemy stats (§23)');
  const rng=makeRng(opts.rngSeed??1),b={time:0,wave,cp,mode,geometry:opts.geometrySensitivity??D.GEOMETRY_SENSITIVITY_PRIMARY,rng,
    heroes:playerState.heroes.map((h,i)=>cloneHero(h,i)),towers:playerState.towers.map((t,i)=>cloneTower(t,i)),enemies:[],projectiles:[],spawnQueue:buildSpawnQueue(wave,cp,boss,rng),spawnTimer:0,
    barricades:Array.from({length:D.LAYOUT.LANES},()=>({hp:0})),castle:{maxHP:D.castleMaxHP(wave-1),hp:D.castleMaxHP(wave-1)},metrics:initMetrics(),events:[]};
  b.initial={heroes:b.heroes.map(h=>({cls:h.cls,maxHP:h.maxHP})),towers:b.towers.map(t=>({type:t.type,maxHP:t.maxHP,resource:t.resource,maxResource:t.maxResource}))};
  while(b.time<D.MAX_SIM_TIME&&!battleOver(b))tick(b,D.TICK_SIZE);
  if(b.time>=D.MAX_SIM_TIME)b.metrics.timedOut=true;
  b.metrics.victory=b.castle.hp>0&&b.spawnQueue.length===0&&b.enemies.length===0;
  b.metrics.failureCause=primaryFailure(b);
  b.metrics.heroDeaths=b.initial.heroes.length-b.heroes.length;b.metrics.towerDeaths=b.initial.towers.length-b.towers.length;
  b.metrics.castleHpRemaining=b.castle.hp;b.metrics.castleHpFraction=b.castle.hp/b.castle.maxHP;
  b.metrics.heroDamageTotal=Object.entries(b.metrics.damageToEnemies).filter(([k])=>k.startsWith('H')).reduce((a,[,v])=>a+v,0);
  b.metrics.towerDamageTotal=Object.entries(b.metrics.damageToEnemies).filter(([k])=>k.startsWith('T')).reduce((a,[,v])=>a+v,0);
  b.metrics.equipmentProjection=playerState.meta?.equipmentScenario!=='E0';return b;
}
function tick(b,dt){b.time+=dt;spawnStep(b,dt);enemyStep(b,dt);towerStep(b,dt);heroStep(b,dt);projectileStep(b,dt);cleanup(b)}
function spawnStep(b,dt){if(!b.spawnQueue.length)return;b.spawnTimer-=dt;if(b.spawnTimer>0)return;b.enemies.push(makeEnemy(b.spawnQueue.shift(),b));b.spawnTimer=D.SPAWN_INTERVAL}
function enemyStep(b,dt){for(const e of b.enemies){if(e.hp<=0)continue;e.atkCd-=dt;
  if(e.boss){e.abilityCd-=dt;if(e.abilityCd<=0){const q=nearestDefender(e,b,D.BOSS.attackRange);if(q){e.abilityCd=D.BOSS.abilityCooldown;for(let i=0;i<2;i++)b.enemies.push(makeEnemy({key:'skeleton',tier:'specialized'},b));launchNapalm(e,q,b)}else e.abilityCd=1}}
  if(e.key==='warlock'){e.drainCd-=dt;if(e.drainCd<=0){const t=nearestTower(e,b,D.WARLOCK_DRAIN_RANGE);if(t){const n=Math.min(t.resource,Math.max(D.WARLOCK_DRAIN_FLOOR,Math.ceil(t.maxResource*D.WARLOCK_DRAIN_FRACTION)));t.resource-=n;t.debuff=D.WARLOCK_DEBUFF_DURATION;e.drainCd=D.WARLOCK_DRAIN_INTERVAL}else e.drainCd=1}}
  const q=enemyTactical(e,b),boost=commanderBoost(e,b),speed=e.speed*(D.TACTICAL_SPEED_MOD[e.key]??1)*boost;
  if(q&&['reaper','orc','lieutenant','ghost','darkElf'].includes(e.key)){const d=dist(e,q.obj),ar=e.key==='reaper'?34:e.key==='darkElf'?38:30;if(d<=ar){if(e.atkCd<=0){enemyAttack(e,q,b);e.atkCd=e.key==='reaper'?.72:e.key==='darkElf'?.8:e.key==='orc'?1.15:.9}continue}const pr=e.key==='reaper'?260:e.key==='darkElf'?300:150;if(d<=pr){moveToward(e,q.obj,speed*dt);continue}}
  const bar=b.barricades[e.lane];if(!e.floats&&bar.hp>0&&Math.abs(e.y-D.LAYOUT.WALL_Y)<16&&e.y<D.LAYOUT.WALL_Y+4){if(e.atkCd<=0){bar.hp=Math.max(0,bar.hp-e.damage);e.hp=Math.max(0,e.hp-D.BARRICADE.collisionDamage);e.atkCd=e.key==='orc'?1.15:e.key==='goblin'?.65:.8;if(e.hp<=0)killEnemy(e,null,b)}continue}
  let block=e.objective==='towers'?nearestTower(e,b,46):null;if(!block)block=nearestHeroEntity(e,b,30);if(block){if(e.atkCd<=0){enemyAttack(e,block,b);e.atkCd=e.key==='reaper'?.72:e.key==='goblin'?.65:e.key==='orc'?1.15:1}continue}
  e.y+=speed*dt;if(e.y>=D.LAYOUT.CASTLE_Y){damageCastle(e.damage*D.CASTLE_DAMAGE_MULT,b);killEnemy(e,null,b,true)}
}}
function towerStep(b,dt){for(const t of b.towers){if(t.hp<=0)continue;t.debuff=Math.max(0,t.debuff-dt);t.cd-=dt;if(t.underfunded)t.hp=Math.max(0,t.hp-t.maxHP*D.UNDERFUNDED.hpLossPerMin*dt/60);if(t.cd>0||t.resource<t.shotCost)continue;const q=selectTowerTarget(t,b);if(!q){t.cd=.1;continue}t.resource-=t.shotCost;t.shots++;b.metrics.towerShots['T'+t.slot]=(b.metrics.towerShots['T'+t.slot]||0)+1;b.metrics.towerResourceSpent['T'+t.slot]=(b.metrics.towerResourceSpent['T'+t.slot]||0)+t.shotCost;const dmg=t.damage*(t.debuff>0?D.WARLOCK_DEBUFF_MULT:1)*(t.underfunded?D.UNDERFUNDED.damageMult:1);launchProjectile(t,q,dmg,t.damageType,t.magic?D.TOWER_PROJECTILE_SPEED_MAGIC:D.TOWER_PROJECTILE_SPEED_PHYS,b,false);t.cd=1/(t.fireRate*(t.underfunded?D.UNDERFUNDED.fireRateMult:1))}}
function heroStep(b,dt){for(const h of b.heroes){if(h.hp<=0)continue;h.cd-=dt;if(h.protect>0){h.protect-=dt;continue}const cfg=h.attackConfig;if(h.magic&&/Support|Heal|Barrier/i.test(cfg)){if(h.cd<=0)supportHero(h,cfg,b);continue}const breached=b.enemies.some(e=>e.hp>0&&e.y>D.LAYOUT.GATE_Y),nearby=b.enemies.some(e=>e.hp>0&&dist(h,e)<=220);if(!breached&&!nearby)continue;const q=selectHeroTarget(h,b);if(!q)continue;if(h.range<D.MELEE_RANGE_THRESHOLD){const d=dist(h,q);if(d>h.range-6)moveToward(h,q,155*dt);else if(h.cd<=0){fireHero(h,q,b);h.cd=h.rate}}else if(h.cd<=0){fireHero(h,q,b);h.cd=h.rate}}}
function fireHero(h,q,b){const dt=h.cls==='Knight'?'knight_melee':h.cls==='Rouge'?'rouge_melee':h.cls==='Archer'?'archer_ranged':'arcane';if(h.range<D.MELEE_RANGE_THRESHOLD)applyEnemyDamage(q,critDamage(h.attack,h,b),dt,b,'H'+h.i,h);else launchProjectile(h,q,h.attack,dt,h.magic?D.HERO_PROJ_SPEED_MAGIC:D.HERO_PROJ_SPEED_PHYS,b,true)}
function projectileStep(b,dt){for(const p of b.projectiles){const dx=p.tx-p.x,dy=p.ty-p.y,d=Math.hypot(dx,dy),step=p.speed*dt*b.geometry;if(d<=step||!p.target||p.target.hp<=0){if(p.kind==='napalm')explodeNapalm(p,b);else if(p.target?.hp>0)applyEnemyDamage(p.target,critDamage(p.damage,p.source,b),p.damageType,b,p.sourceId,p.source);p.dead=true}else{p.x+=dx/d*step;p.y+=dy/d*step}}b.projectiles=b.projectiles.filter(p=>!p.dead)}
function applyEnemyDamage(e,raw,type,b,sid,source){if(e.hp<=0)return;const a=enemyAffinity(e,type);if(a<=0){b.metrics.immuneHits++;return}const d=raw*a;e.hp=Math.max(0,e.hp-d);e.dmgBy[sid]=(e.dmgBy[sid]||0)+d;b.metrics.damageToEnemies[sid]=(b.metrics.damageToEnemies[sid]||0)+d;if(e.hp<=0)killEnemy(e,sid,b)}
function applyDefenderDamage(t,raw,type,b,source){if(t.hp<=0)return;if(t.team==='hero'){if(b.rng()<D.dodgeChance(t.agility)){b.metrics.dodges++;return}let d=D.damageAfterDefense(raw,t.defense);if(t.shield){const s=Math.min(t.shield,d);t.shield-=s;d-=s}t.hp=Math.max(0,t.hp-d);b.metrics.damageToHeroes+=d;if(source?.boss)source.hp=Math.min(source.maxHP,source.hp+d*D.BOSS.lifestealFraction)}else{const d=raw*(source?.key==='darkElf'?D.DARK_ELF_TOWER_DAMAGE_MULT:1);t.hp=Math.max(0,t.hp-d);b.metrics.damageToTowers+=d}}
function enemyAttack(e,q,b){if(q.kind==='tower')applyDefenderDamage(q.obj,e.damage,null,b,e);else{if(e.key==='warlock')q.obj.shield=0;applyDefenderDamage(q.obj,e.damage,null,b,e)}}
function launchProjectile(s,q,damage,type,speed,b,isHero){b.projectiles.push({kind:'normal',sourceId:isHero?'H'+s.i:'T'+s.slot,x:s.x,y:s.y,tx:q.x,ty:q.y,target:q,speed,damage,damageType:type,source:s})}
function launchNapalm(e,q,b){b.projectiles.push({kind:'napalm',sourceId:'E'+e.key,x:e.x,y:e.y,tx:q.obj.x,ty:q.obj.y,target:q.obj,speed:D.BOSS.napalmProjectileSpeed,damage:e.damage*D.BOSS.napalmDamageMult,splash:D.BOSS.napalmSplashRadius,source:e})}
function explodeNapalm(p,b){for(const h of b.heroes)if(h.hp>0&&dist(p,h)<=p.splash)applyDefenderDamage(h,p.damage*(1-D.BOSS.napalmFalloffMax*(dist(p,h)/p.splash)),'fire',b,p);for(const t of b.towers)if(t.hp>0&&dist(p,t)<=p.splash)applyDefenderDamage(t,p.damage*(1-D.BOSS.napalmFalloffMax*(dist(p,t)/p.splash)),'fire',b,p)}
function selectHeroTarget(h,b){const pool=b.enemies.filter(e=>e.hp>0&&dist(h,e)<=(h.range<D.MELEE_RANGE_THRESHOLD?220:h.range));if(!pool.length)return null;const c=h.attackConfig;if(/Weakest|Assassinate/i.test(c))return pool.reduce((a,e)=>e.hp<a.hp?e:a);if(/Sniper|strongest/i.test(c))return pool.reduce((a,e)=>e.maxHP>a.maxHP?e:a);if(/Guard|Defensive/i.test(c))return pool.reduce((a,e)=>e.y>a.y?e:a);if(h.cls==='Mage'){const v=pool.filter(e=>enemyAffinity(e,'arcane')>0);if(!v.length)return null;return v.reduce((a,e)=>enemyAffinity(e,'arcane')>enemyAffinity(a,'arcane')||enemyAffinity(e,'arcane')===enemyAffinity(a,'arcane')&&e.hp<a.hp?e:a)}return pool.reduce((a,e)=>dist(h,e)<dist(h,a)?e:a)}
function selectTowerTarget(t,b){const p=b.enemies.filter(e=>e.hp>0&&dist(t,e)<=t.range);if(!p.length)return null;if(t.priority==='elite_boss')return p.slice().sort((a,e)=>tierRank(e)-tierRank(a)||e.maxHP-a.maxHP)[0];if(t.priority==='vulnerable'){const v=p.filter(e=>enemyAffinity(e,t.damageType)>0);return v.length?v.slice().sort((a,e)=>enemyAffinity(e,t.damageType)-enemyAffinity(a,t.damageType)||a.hp-e.hp)[0]:null}if(t.priority==='cluster')return p.slice().sort((a,e)=>cluster(e,b)-cluster(a,b))[0];return p.reduce((a,e)=>dist(t,e)<dist(t,a)?e:a)}
function cluster(e,b){return b.enemies.filter(x=>x.hp>0&&x!==e&&dist(e,x)<=55).length}function tierRank(e){return e.boss?3:e.tier==='elite'?2:1}
function enemyTactical(e,b){if(e.key==='reaper'){let x=null,w=Infinity;for(const h of b.heroes)if(h.hp>0&&dist(e,h)<=260){const f=h.hp/h.maxHP;if(f<w){w=f;x=h}}return x?{kind:'hero',obj:x}:null}if(e.key==='orc')return nearestTower(e,b,150)||nearestHeroEntity(e,b,110);if(e.key==='lieutenant')return nearestHeroEntity(e,b,150)||nearestTower(e,b,120);if(e.key==='ghost')return nearestHeroEntity(e,b,120)||nearestTower(e,b,120);if(e.key==='darkElf')return nearestTower(e,b,300)||nearestHeroEntity(e,b,140);if(e.key==='warlock')return nearestHeroEntity(e,b,100);return null}
function commanderBoost(e,b){return b.enemies.some(x=>x.hp>0&&x.tier==='elite'&&dist(e,x)<=D.LIEUTENANT_AURA_RADIUS)?D.LIEUTENANT_AURA_MULT:1}
function nearestTower(e,b,r){let x=null,d0=r;for(const t of b.towers)if(t.hp>0){const d=dist(e,t);if(d<=d0){d0=d;x=t}}return x?{kind:'tower',obj:x}:null}
function nearestHeroEntity(e,b,r){let x=null,d0=r;for(const h of b.heroes)if(h.hp>0){const d=dist(e,h);if(d<=d0){d0=d;x=h}}return x?{kind:'hero',obj:x}:null}
function nearestDefender(e,b,r){let best=null,bd=r;for(const h of b.heroes)if(h.hp>0){const d=dist(e,h);if(d<=bd){bd=d;best={kind:'hero',obj:h}}}for(const t of b.towers)if(t.hp>0){const d=dist(e,t);if(d<=bd){bd=d;best={kind:'tower',obj:t}}}return best}
function supportHero(h,c,b){let x=null,w=Infinity;for(const a of b.heroes)if(a.hp>0&&a.hp/a.maxHP<w){w=a.hp/a.maxHP;x=a}if(!x)return;if(/Barrier/i.test(c))x.shield=Math.min(x.maxHP*.25,(x.shield||0)+28*h.healPower);else if(x.hp<x.maxHP)x.hp=Math.min(x.maxHP,x.hp+34*h.healPower);h.cd=h.rate}
function damageCastle(d,b){b.castle.hp=Math.max(0,b.castle.hp-d);b.metrics.castleHits++;if(b.castle.hp<=0)b.metrics.castleBreached=true}
function killEnemy(e,sid,b){if(e.dead)return;e.dead=true;e.hp=0;b.metrics.kills++;b.metrics.killsByType[e.key]=(b.metrics.killsByType[e.key]||0)+1;const t=e.tier==='boss'?{xp:600,gold:150}:e.tier==='elite'?{xp:60,gold:20}:e.tier==='specialized'?{xp:20,gold:7}:{xp:10,gold:4};b.metrics.goldEarned+=t.gold;const total=Object.values(e.dmgBy).reduce((a,v)=>a+v,0)||1;if(e.tier==='boss')for(const [k,v] of Object.entries(e.dmgBy))b.metrics.xpBySource[k]=(b.metrics.xpBySource[k]||0)+t.xp*v/total;else{let best=null,bd=-1;for(const [k,v] of Object.entries(e.dmgBy))if(v>bd){bd=v;best=k}for(const h of b.heroes)if(h.hp>0)b.metrics.xpBySource['H'+h.i]=(b.metrics.xpBySource['H'+h.i]||0)+t.xp*D.XP_LIVING_HERO_SHARE;if(best)b.metrics.xpBySource[best]=(b.metrics.xpBySource[best]||0)+t.xp}}
function buildSpawnQueue(w,c,boss,rng){const n=D.enemyCount(w,c),cap=D.specialistCap(w,c),o=[],basic=['ghost','slime','goblin'],spec=['skeleton','orc','reaper','darkElf','warlock'],obj=['castle','towers','resources','castle','squad'],g=D.groups(w),ws=D.GROUP_WEIGHTS.slice(0,g),sum=ws.reduce((a,v)=>a+v,0);for(let gi=0;gi<g;gi++){const m=Math.max(1,Math.round(n*(ws[gi]/sum)));for(let i=0;i<m;i++){const sp=rng()<cap,a=(sp?spec:basic),k=a[Math.floor(rng()*a.length)];o.push({key:k,tier:sp?'specialized':'basic',objective:obj[gi%obj.length]})}}for(let i=0;i<D.eliteCount(w);i++)o.push({key:'lieutenant',tier:'elite',objective:'squad'});if(boss)o.push({key:{ThreeHeadedDemon:'demon',ImperialNecromancer:'imperialNecromancer',NuclearBehemoth:'nuclearBehemoth'}[boss],tier:'boss',boss:true,objective:'castle'});return o}
function makeEnemy(s,b){const c=D.ENEMY_CATALOG[s.key];if(!c)throw new Error(`DECLARATION MISSING: enemy ${s.key} (§20)`);const e={team:'enemy',key:s.key,tier:s.tier||c.tier,boss:!!s.boss||!!c.boss,hp:c.hp*D.hpScale(b.wave,b.cp),maxHP:c.hp*D.hpScale(b.wave,b.cp),damage:c.damage*D.damageScale(b.wave,b.cp),speed:c.speed,floats:!!c.floats,objective:s.objective||'castle',lane:pickLane(b),x:0,y:0,atkCd:s.boss?0:1,abilityCd:s.boss?D.BOSS.initialAbilityCooldown:s.key==='warlock'?3:0,drainCd:s.key==='warlock'?3:0,dmgBy:{},dead:false};e.x=laneX(e.lane);return e}
function pickLane(b){let best=0,cost=Infinity;for(let l=0;l<D.LAYOUT.LANES;l++){let c=b.barricades[l].hp;for(const t of b.towers)if(t.hp>0&&Math.abs(t.x-laneX(l))<90)c+=t.damage*3;c+=b.rng()*40;if(c<cost){cost=c;best=l}}return best}function laneX(i){return D.LAYOUT.W/D.LAYOUT.LANES*(i+.5)}
function cloneHero(h,i){return {team:'hero',i,cls:h.cls,level:h.level,stats:{...h.stats},maxHP:h.maxHP,hp:h.maxHP,attack:h.attack,range:h.range,rate:h.rate,magic:h.magic,agility:h.stats.agility,defense:h.stats.defense,healPower:1+h.stats.intelligence/100,attackConfig:h.attackConfig||D.HERO_DEFAULT_CONFIG[h.cls],x:D.LAYOUT.W*((i+.5)/4),y:D.LAYOUT.HERO_Y,cd:0,shield:0,equipmentCritChance:h.equipmentCritChance||0,equipmentCritDamage:h.equipmentCritDamage||0}}
function cloneTower(t,i){const c=D.TOWER[t.type];if(!c)throw new Error(`DECLARATION MISSING: tower ${t.type} (§13)`);const cm=Math.pow(1.1,t.level-1),rm=Math.pow(1.12,t.level-1),hp=Math.round(c.baseHp*cm),mr=Math.round(c.maxResource*rm);return {team:'tower',slot:i,type:t.type,level:t.level,maxHP:hp,hp:hp,damage:c.damage*cm,fireRate:c.fireRate,range:c.range,damageType:c.damageType,magic:c.magic,splash:c.splash,priority:D.TOWER_TARGETING_MODE[t.type],resource:mr,maxResource:mr,shotCost:c.shotCost,cd:0,shots:0,debuff:0,underfunded:!!t.underfunded,x:D.SLOT_POS[i]?.x??210,y:D.SLOT_POS[i]?.y??342}}
function critDamage(d,h,b){if(h.equipmentCritChance)b.metrics.equipmentCritUnresolved=true;return b.rng()<D.BASE_CRIT_CHANCE?d*D.CRIT_MULTIPLIER:d}
function enemyAffinity(e,type){return D.AFFINITY[D.ENEMY_AFFINITY[e.key]?.[type]??'normal']}
function moveToward(a,b,s){const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1;a.x+=dx/d*s;a.y+=dy/d*s}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function cleanup(b){b.enemies=b.enemies.filter(e=>e.hp>0&&!e.dead);b.heroes=b.heroes.filter(h=>h.hp>0);b.towers=b.towers.filter(t=>t.hp>0)}
function battleOver(b){return b.castle.hp<=0||(b.heroes.length===0&&b.towers.length===0)||(b.spawnQueue.length===0&&b.enemies.length===0)}
function primaryFailure(b){if(b.metrics.victory)return null;if(b.castle.hp<=0)return'castle_breach';if(!b.heroes.length&&!b.towers.length)return'all_defenders_dead';if(b.metrics.timedOut)return'timeout';if(b.towers.some(t=>t.resource<t.shotCost)&&b.heroes.length)return'tower_resource_exhaustion';return'combat_incomplete'}
function initMetrics(){return {victory:false,timedOut:false,castleBreached:false,castleHits:0,castleHpRemaining:0,castleHpFraction:0,heroDeaths:0,towerDeaths:0,damageToEnemies:{},damageToHeroes:0,damageToTowers:0,heroDamageTotal:0,towerDamageTotal:0,towerShots:{},towerResourceSpent:{},kills:0,killsByType:{},xpBySource:{},goldEarned:0,immuneHits:0,dodges:0,crits:0,equipmentCritUnresolved:false}}
function makeRng(seed){let s=typeof seed==='string'?hash(seed):seed>>>0;return()=>{s=(1664525*s+1013904223)>>>0;return s/4294967296}}function hash(s){let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0}
